########################################
## Custom models
########################################

Model\ActiveCalls:
  itemOperations:
    get_my_active_calls:
      access_control: '"ROLE_SUPER_ADMIN" in roles && user.hasAccessPrivileges(_api_resource_class, request.getMethod())'
      method: 'GET'
      path: '/my/active_calls'
      route_name: 'get_my_active_calls'
      parameters: []
      swagger_context:
        produces:
        - 'application/json'
        tags:
        - My
        parameters:
        - name: brand
          in: query
          type: integer
          required: false
          description: 'Brand Id'
  collectionOperations: []
