Ivoz\Cgr\Domain\Model\TpCdrStat\TpCdrStat:
  repositoryClass: Ivoz\Cgr\Infrastructure\Persistence\Doctrine\TpCdrStatDoctrineRepository
  type: entity
  table: tp_cdr_stats
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
