Ivoz\Cgr\Domain\Model\TpCdrStat\TpCdrStatAbstract:
  type: mappedSuperclass
  indexes:
    tpCdrStat_tpid:
      columns:
        - tpid
  fields:
    tpid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'ivozprovider'
    tag:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    queueLength:
      type: integer
      nullable: false
      length: 10
      options:
        fixed: false
        default: 0
      column: queue_length
    timeWindow:
      type: string
      nullable: false
      length: 8
      options:
        fixed: false
        default: ""
      column: time_window
    saveInterval:
      type: string
      nullable: false
      length: 8
      options:
        fixed: false
        default: ""
      column: save_interval
    metrics:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    setupInterval:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: setup_interval
    tors:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
    cdrHosts:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: cdr_hosts
    cdrSources:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: cdr_sources
    reqTypes:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: req_types
    directions:
      type: string
      nullable: false
      length: 8
      options:
        fixed: false
        default: ""
    tenants:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
    categories:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: ""
    accounts:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: ""
    subjects:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
    destinationIds:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: destination_ids
    ppdInterval:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: ppd_interval
    usageInterval:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: usage_interval
    suppliers:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
    disconnectCauses:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: disconnect_causes
    mediationRunids:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: mediation_runids
    ratedAccounts:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: ""
      column: rated_accounts
    ratedSubjects:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: rated_subjects
    costInterval:
      type: string
      nullable: false
      length: 24
      options:
        fixed: false
        default: ""
      column: cost_interval
    actionTriggers:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ""
      column: action_triggers
    createdAt:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: created_at
  manyToOne:
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: tpCdrStats
      joinColumns:
        carrierId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
