Ivoz\Cgr\Domain\Model\TpDerivedCharger\TpDerivedChargerAbstract:
  type: mappedSuperclass
  indexes:
    tpDerivedCharge_tpid:
      columns:
        - tpid
  fields:
    tpid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'ivozprovider'
    loadid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'DATABASE'
    direction:
      type: string
      nullable: false
      length: 8
      options:
        fixed: false
        default: '*out'
    tenant:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    category:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: 'call'
    account:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*any'
    subject:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
        default: '*any'
    destinationIds:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
        default: '*any'
      column: destination_ids
    runid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'carrier'
    runFilters:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: ''
      column: run_filters
    reqTypeField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '^*postpaid'
      column: req_type_field
    directionField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: direction_field
    tenantField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: tenant_field
    categoryField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: category_field
    accountField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'carrierId'
      column: account_field
    subjectField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'carrierId'
      column: subject_field
    destinationField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: destination_field
    setupTimeField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: setup_time_field
    pddField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: pdd_field
    answerTimeField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: answer_time_field
    usageField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: usage_field
    supplierField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: supplier_field
    disconnectCauseField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: disconnect_cause_field
    ratedTimeField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: rated_field
    costField:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*default'
      column: cost_field
    createdAt:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: created_at
  oneToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumn:
        name: brandId
        referencedColumnName: id
        nullable: false
        onDelete: cascade