Ivoz\Cgr\Domain\Model\TpDerivedCharger\TpDerivedCharger:
  repositoryClass: Ivoz\Cgr\Infrastructure\Persistence\Doctrine\TpDerivedChargerDoctrineRepository
  type: entity
  table: tp_derived_chargers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
