Ivoz\Cgr\Domain\Model\TpDestinationRate\TpDestinationRate:
  repositoryClass: Ivoz\Cgr\Infrastructure\Persistence\Doctrine\TpDestinationRateDoctrineRepository
  type: entity
  table: tp_destination_rates
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
