Ivoz\Cgr\Domain\Model\TpLcrRule\TpLcrRule:
  repositoryClass: Ivoz\Cgr\Infrastructure\Persistence\Doctrine\TpLcrRuleDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: tp_lcr_rules
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
