Ivoz\Cgr\Domain\Model\TpLcrRule\TpLcrRuleAbstract:
  type: mappedSuperclass
  indexes:
    tpLcrRule_tpid:
      columns:
        - tpid
  fields:
    tpid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'ivozprovider'
    direction:
      type: string
      nullable: false
      length: 8
      options:
        fixed: false
        default: '*out'
    tenant:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    category:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
    account:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: '*any'
    subject:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
        default: '*any'
    destinationTag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
        default: '*any'
    rpCategory:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
    strategy:
      type: string
      nullable: false
      length: 18
      options:
        fixed: false
        default: '*lowest_cost'
    strategyParams:
      type: string
      nullable: true
      length: 256
      options:
        fixed: false
        default: ''
    activationTime:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
    weight:
      type: decimal
      nullable: false
      precision: 8
      scale: 2
      options:
        fixed: false
        default: 10
    createdAt:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
  oneToOne:
    outgoingRouting:
      targetEntity: \Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRoutingInterface
      fetch: LAZY
      mappedBy: null
      inversedBy: tpLcrRule
      joinColumn:
        name: outgoingRoutingId
        referencedColumnName: id
        onDelete: cascade
        nullable: true
