Ivoz\Cgr\Domain\Model\TpTiming\TpTimingAbstract:
  type: mappedSuperclass
  indexes:
    tpTiming_tpid:
      columns:
        - tpid
    tpTiming_tpid_tmid:
      columns:
        - tpid
        - tag
  uniqueConstraints:
    tpid_tag:
      columns:
        - tpid
        - tag
  fields:
    tpid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'ivozprovider'
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    years:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
    months:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
    monthDays:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: month_days
    weekDays:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: week_days
    time:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: '00:00:00'
    createdAt:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: created_at
  oneToOne:
    ratingPlan:
      targetEntity: \Ivoz\Provider\Domain\Model\RatingPlan\RatingPlanInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: tpTiming
      joinColumns:
        ratingPlanId:
          nullable: false
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false