production:
  entity: Ivoz\Provider\Domain\Model\Administrator\Administrator
  fields: 
    username:
      title: _('Username')
      type: text
      trim: both
      required: true
      maxLength: 65
      default: true
    pass:
      title: _('Password')
      type: password
      adapter: PlainText
      required: true
    name:
      title: _('Name')
      type: text
      trim: both
    lastname:
      title: _('Lastname')
      type: text
      trim: both
    email:
      title: ngettext('Email', 'Emails', 1)
      type: text
      trim: both
      defaultValue:
      maxLength: 100
    active:
      title: _('Active')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
    brand:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Brand.name: asc
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
        'null': _("Unassigned")
    timezone:
      title: _('Timezone')
      type: select
      defaultValue: 145
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Timezone\Timezone
          fieldName: 
            fields: 
              - tz
            template: '%tz%'
          order:
            Timezone.tz: asc
    restricted:
      title: _('Restricted')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
      info:
        type: box
        position: left
        icon: help
        text: _("Restricted administrators have read-only permissions by default. This privileges can be fine-tuned in <i>List of Administrator access privileges</i> subsection. <br><br><b>Global/Brand</b> restricted administrators have no web access and can only be used for API integrations. <br><br><b>Client</b> restricted administrators can be used both for API integrations and limited web access.")
        label: _("Need help?")

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
