production:
  entity: Ivoz\Provider\Domain\Model\CallCsvReport\CallCsvReport
  fields:
    sentTo:
      title: _('Sent to')
      type: text
      trim: both
      required: true
      maxLength: 250
      readonly: true
    inDate:
      title: _('In date')
      type: picker
      required: true
      source:
        control: datetime
        settings:
          disabled: 'false'
      readonly: true
    outDate:
      title: _('Out date')
      type: picker
      required: true
      source:
        control: datetime
        settings:
          disabled: 'false'
      readonly: true
    createdOn:
      title: _('Created on')
      type: picker
      required: true
      source:
        control: datetime
        settings:
          disabled: 'false'
      readonly: true
    csv:
      title: 'CSV'
      type: file
      source:
        data: fso
        size_limit: 20M
        options:
          hiddenName: false
      options:
        commands:
          callCsvReportsCsvDownload_command: ${auth.acls.CallCsvReports.read}
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
