production:
  entity: Ivoz\Provider\Domain\Model\DdiProvider\DdiProvider
  fields:
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      default: true
    description:
      title: _('Description')
      type: text
      trim: both
      defaultValue:
    brand:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Brand.name: asc
    transformationRuleSet:
      title: _('Numeric transformation')
      type: select
      defaultValue: 252
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSet
          filterClass: IvozProvider_Klear_Filter_TransformationRuleSets
          fieldName:
            fields:
              - name${lang}
            template: '%name${lang}%'
          order:
            TransformationRuleSet.name.${lang}: asc
    proxyTrunk:
      title: _('Local socket')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\ProxyTrunk\ProxyTrunk
          filterClass: IvozProvider_Klear_Filter_ProxyTrunks
          fieldName:
            fields:
            - ip
            template: '%ip%'
          order:
            ProxyTrunk.id: asc
      info:
        type: box
        position: left
        icon: help
        text: _("Local address used in SIP signalling with this DDI Provider.")
        label: _("Need help?")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
