production:
  entity: Ivoz\Provider\Domain\Model\DdiProviderAddress\DdiProviderAddress
  fields:
    ip:
      title: _('IP Address')
      type: text
      maxLength: 50
      default: true
      required: true
    description:
      title: _('Description')
      type: text
      maxLength: 200
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
