production:
  entity: \Ivoz\Provider\Domain\Model\Domain\Domain
  fields: 
    domain:
      title: _('Domain')
      type: text
      trim: both
      required: true
      maxLength: 255
      default: true
    brand:
      title: _('Brand')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_Domains
        method: getBrand
    company:
      title: _('Client')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_Domains
        method: getClient

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
