production:
  entity: Ivoz\Provider\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUser
  fields: 
    huntGroup:
      title: ngettext('Hunt Group', 'Hunt Groups', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\HuntGroup\HuntGroup
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            HuntGroup.name: asc
      default: true
    routeType:
      title: _('Target type')
      type: select
      required: true
      source:
        data: inline
        values:
          'user':
            title: ngettext('User', 'Users', 1)
            visualFilter:
              show: [ user ]
              hide: [ numberCountry, numberValue]
          'number':
            title: _('Number')
            visualFilter:
              show: [ numberCountry, numberValue]
              hide: [ user]
    numberCountry:
      title: _('Country')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
    numberValue:
      title: _('Number')
      type: text
      trim: both
      required: true
    user:
      title: ngettext('User', 'Users', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\User\User
          filterClass: IvozProvider_Klear_Filter_HuntGroupsRelUsers
          fieldName: 
            fields: 
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
    timeoutTime:
      title: _('Timeout time')
      type: number
      source:
        control: Spinner
    priority:
      title: _('Priority')
      type: number
      source:
        control: Spinner
    target:
      title: _('Target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_RouteTarget
        method: getTarget
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
