production:
  entity: Ivoz\Kam\Domain\Model\UsersCdr\UsersCdr
  fields:
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
        'null': _("Unassigned")
    startTime:
      title: _('Start time')
      type: picker
      defaultValue: 2000-01-01 00:00:00
      source:
        control: datetime
        settings:
          disabled: 'false'
    duration:
      title: _('Duration')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_UsersCdr
        method: getDuration
    direction:
      title: _('Direction')
      type: select
      source:
        data: inline
        values:
          'inbound':
            title: _("Inbound")
          'outbound':
            title: _("Outbound")
    caller:
      title: _('Source')
      type: text
    callee:
      title: _('Destination')
    callid:
      title: _('Callid')
      type: text
    xcallid:
      title: _('Xcallid')
      type: text
    callidHash:
      title: _('CallidHash')
      type: text
    owner:
      title: _('Owner')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_UsersCdr
        method: getCallOwner
    party:
      title: _('Party')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_UsersCdr
        method: getCallParty
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
