production:
  entity: Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRouting
  fields:
    type:
      title: _('Type')
      type: select
      defaultValue: pattern
      source:
        data: inline
        values:
          'pattern':
            title: _('Pattern')
            visualFilter:
              show: ["routingPattern"]
              hide: ["routingPatternGroup"]
          'group':
            title: _('Group')
            visualFilter:
              show: ["routingPatternGroup" ]
              hide: ["routingPattern"]
          'fax':
            title: _('Fax')
            visualFilter:
              hide: ["routingPattern","routingPatternGroup"]
              show: []
    routingTag:
      title: ngettext('Routing Tag', 'Routing Tags', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\RoutingTag\RoutingTag
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
              - tag
            template: '%name% (%tag%)'
          order:
            RoutingTag.name: asc
        'null': _("Unassigned")
    routingPattern:
      title: _('Select destination pattern')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\RoutingPattern\RoutingPattern
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name${lang}
              - description${lang}
              - prefix
            template: '%name${lang}% %description${lang}% (%prefix%)'
          order:
            RoutingPattern.name.${lang}: asc
    routingPatternGroup:
      title: _('Select destination group')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroup
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            RoutingPatternGroup.name: asc
    carrier:
      title: ngettext('Carrier', 'Carriers', 0)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Carrier\Carrier
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Carrier.name: asc
    relCarriers:
      title: ngettext('Carrier', 'Carriers', 1)
      type: multiselect
      required: true
      source:
        data: mapper
        config:
          filterClass: IvozProvider_Klear_Filter_Brand
          relation: \Ivoz\Provider\Domain\Model\OutgoingRoutingRelCarrier\OutgoingRoutingRelCarrier
          relationProperty: outgoingRouting
          relatedProperty: carrier
          related: \Ivoz\Provider\Domain\Model\Carrier\Carrier
          filterClass: IvozProvider_Klear_Filter_CarriersCost
          relatedFieldName:
            fields:
              - name
            template: '%name%'
          order:
            Carrier.name: asc
    carriersGhost:
      title: ngettext('Carrier', 'Carriers', 1)
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_OutgoingRouting
        method: getCarriers
    priority:
      title: _('Priority')
      type: number
      defaultValue: 1
      required: true
      source:
        control: Spinner
        min: 1
        max: 254
    weight:
      title: _('Weight')
      type: number
      required: true
      defaultValue: 1
      source:
        control: Spinner
        min: 1
        max: 20
    routingMode:
      title: _('Route type')
      type: select
      source:
        data: inline
        filterClass: IvozProvider_Klear_Filter_OutgoingRoutingMode
        values:
          'static':
            title: _("Static")
            visualFilter:
              show: [ carrier, prefix, forceClid, clidCountry, clid, weight, priority ]
              hide: [ relCarriers ]
          'lcr':
            title: _("LCR")
            visualFilter:
              show: [ relCarriers, weight, priority ]
              hide: [ carrier, prefix, forceClid, clidCountry, clid ]
          'block':
            title: _("Block")
            visualFilter:
              show: [ ]
              hide: [ carrier, prefix, forceClid, clidCountry, clid, relCarriers, weight, priority, stopper]
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
        'null': _("Apply to all clients")
      default: true
    target:
      title: _('Destination')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_OutgoingRouteType
        method: getData
    prefix:
      title: _('Destination prefix')
      type: text
      trim: both
      maxLength: 25
      required: false
      info:
        type: box
        position: left
        icon: help
        text: _("This prefix will be added to the callee after carrier's numeric transformations.")
        label: _("Need help?")
    clid:
      title: _('Clid')
      type: text
      trim: both
      maxLength: 25
      required: true
    stopper:
      title: _('Stopper')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '1':
            title: _("Yes")
          '0':
            title: _("No")
      info:
        type: box
        position: left
        icon: help
        text: _("Routes with higher priority won't be evaluated. Those with same priority will be evaluated.")
        label: _("Need help?")
    forceClid:
      title: _('Force Clid')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '1':
            title: _("Yes")
            visualFilter:
              show: [ clid, clidCountry ]
              hide: []
          '0':
            title: _("No")
            visualFilter:
              show: []
              hide: [ clid, clidCountry ]
      info:
        type: box
        position: left
        icon: help
        text: _("Instead of getting the caller from PAI/RPID headers, this clid will be used (and will be adapted using carrier's numeric transformations).")
        label: _("Need help?")
    clidCountry:
      title: _('Country')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
