production:
  entity: Ivoz\Provider\Domain\Model\RatingPlan\RatingPlan
  fields:
    id:
      title: ngettext('Id', 'Ids', 1)
      required: false
    ratingPlanGroup:
      title: ngettext('Rating plan', 'Rating plans', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\RatingPlanGroup\RatingPlanGroup
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name${lang}
            template: '%name${lang}%'
          order:
            RatingPlanGroup.name.${lang}: asc
    destinationRateGroup:
      title: ngettext('Destination rate', 'Destination rates', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\DestinationRateGroup\DestinationRateGroup
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name${lang}
            template: '%name${lang}%'
          order:
            DestinationRateGroup.name.${lang}: asc
    weight:
      title: _('Weight')
      type: number
      defaultValue: 1
      required: true
      source:
        control: Spinner
        min: 1
        step: 1
      info:
        type: box
        position: left
        icon: help
        text: _("In case of colliding prefixes, destination rate with highest weight will be used.")
        label: _("Need help?")
    timingType:
      title: _('Timing type')
      type: select
      source:
        data: inline
        values:
          'always':
            title: _("Always")
            visualFilter:
              show: [ ]
              hide: &timingFields
                - timeIn
                - monday
                - tuesday
                - wednesday
                - thursday
                - friday
                - saturday
                - sunday
          'custom':
            title: _("Custom")
            visualFilter:
              show:
                <<: *timingFields
              hide: []
    timeIn:
      title: _('Time in')
      type: picker
      required: true
      defaultValue: 00:00:00
      source:
        control: time
        settings:
          disabled: 'false'
    monday:
      title: _('Monday')
      type: checkbox
      defaultValue: 1
    tuesday:
      title: _('Tuesday')
      type: checkbox
      defaultValue: 1
    wednesday:
      title: _('Wednesday')
      type: checkbox
      defaultValue: 1
    thursday:
      title: _('Thursday')
      type: checkbox
      defaultValue: 1
    friday:
      title: _('Friday')
      type: checkbox
      defaultValue: 1
    saturday:
      title: _('Saturday')
      type: checkbox
      defaultValue: 1
    sunday:
      title: _('Sunday')
      type: checkbox
      defaultValue: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
