production:
  entity: Ivoz\Provider\Domain\Model\RatingProfile\RatingProfile
  fields: 
    activationTime:
      title: _('Activation time')
      type: picker
      required: true
      source:
        control: datetime
        settings:
          disabled: 'false'
    ratingPlanGroup:
      title: ngettext('Rating plan', 'Rating plans', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\RatingPlanGroup\RatingPlanGroup
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name${lang}
            template: '%name${lang}%'
          order:
            RatingPlanGroup.name.${lang}: asc
      default: true
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
        'null': _("Unassigned")
    routingTag:
      title: ngettext('Routing Tag', 'Routing Tags', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\RoutingTag\RoutingTag
          filterClass: IvozProvider_Klear_Filter_RouteTag
          fieldName:
            fields:
              - name
              - tag
            template: '%name% (%tag%)'
          order:
            RoutingTag.name: asc
        'null': _("No routing tag")

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
