production:
  entity: \Ivoz\Provider\Domain\Model\WebPortal\WebPortal
  fields: 
    brand:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    url:
      title: ngettext('URL', 'URLs', 1)
      type: text
      pattern: "^https://[^/]*$"
      trim: both
      required: true
      maxLength: 255
      info:
        type: box
        position: left
        icon: help
        text: _("'https://' URLs valid only (without trailing '/')")
        label: _("Need help?")
    klearTheme:
      title: ngettext('Theme', 'Themes', 1)
      type: select
      defaultValue: redmond
      source:
        data: themes
    urlType:
      title: _('URL type')
      type: select
      required: true
      source:
        data: inline
        values:
          'god':
            title: _('God')
            visualFilter:
              show: ["klearTheme"]
              hide: ["userTheme"]
          'brand':
            title: ngettext('Brand', 'Brands', 1)
            visualFilter:
              show: ["klearTheme"]
              hide: ["userTheme"]
    name:
      title: _('Name')
      type: text
      trim: both
      default: true
      defaultValue:
      maxLength: 200
      info:
        type: box
        position: left
        icon: help
        text: _("Will be shown on page footer")
        label: _("Need help?")
    logo:
      title: _('Logo')
      type: file
      source:
        data: fso
        size_limit: 20M
        options:
          hiddenName: true
          download:
            external: true
            type: command
            target: webPortalsLogoDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          delete:
            type: setNullFso
            icon: ui-silk-bin
            title: _("Delete file")
            onNull: hide
          upload:
            type: command
            target: webPortalsLogoUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
          preview:
            target: webPortalsLogoPreview_command
            type: command
            class: filePreview
            external: 1
            props:
              width: 150
              height: 150
              crop: false
            onNull: hide
          previewList:
            target: webPortalsLogoPreview_command
            type: command
            class: filePreview
            listController: 1
            external: 1
            props:
              width: 30
              height: 30
              crop: false
            onNull: hide
staging: 
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
