blank_issues_enabled: false
contact_links:
  - name: IvozProvider Users Google Group
    url: https://groups.google.com/forum/#!forum/ivozprovider-users
    about: If you have trouble with your environment or a user question, please post them here
