services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Cgr\Infrastructure\Cgrates\Service\CompanyBalanceService: ~
  Ivoz\Provider\Domain\Service\Company\CompanyBalanceServiceInterface:
    alias: Ivoz\Cgr\Infrastructure\Cgrates\Service\CompanyBalanceService
    public: true

  Ivoz\Cgr\Infrastructure\Cgrates\Service\CarrierBalanceService: ~
  Ivoz\Provider\Domain\Service\Carrier\CarrierBalanceServiceInterface:
    alias: Ivoz\Cgr\Infrastructure\Cgrates\Service\CarrierBalanceService
    public: true

  Ivoz\Cgr\Infrastructure\Cgrates\Service\LoadTpAccountAction:  ~
  Ivoz\Cgr\Domain\Service\TpAccountAction\LoadTpAccountActionInterface:
    '@Ivoz\Cgr\Infrastructure\Cgrates\Service\LoadTpAccountAction'

  Ivoz\Cgr\Infrastructure\Cgrates\Service\RemoveTpAccountAction:  ~
  Ivoz\Cgr\Domain\Service\TpAccountAction\RemoveTpAccountActionInterface:
    '@Ivoz\Cgr\Infrastructure\Cgrates\Service\RemoveTpAccountAction'

  Ivoz\Cgr\Infrastructure\Cgrates\Service\LoadTpRatingProfile:  ~
  Ivoz\Cgr\Domain\Service\TpRatingProfile\LoadTpRatingProfileInterface:
    '@Ivoz\Cgr\Infrastructure\Cgrates\Service\LoadTpRatingProfile'

  Ivoz\Cgr\Infrastructure\Cgrates\Service\RemoveTpRatingProfile:  ~
  Ivoz\Cgr\Domain\Service\TpRatingProfile\RemoveTpRatingProfileInterface:
    '@Ivoz\Cgr\Infrastructure\Cgrates\Service\RemoveTpRatingProfile'

  Ivoz\Cgr\Infrastructure\Cgrates\Service\RerateCallService:
    public: true
  Ivoz\Kam\Domain\Service\TrunksCdr\RerateCallServiceInterface:
    '@Ivoz\Cgr\Infrastructure\Cgrates\Service\RerateCallService'

  Ivoz\Cgr\Infrastructure\Cgrates\Service\FetchCallStatsService: ~
  Ivoz\Cgr\Domain\Service\TpCdrStat\FetchCallStatsServiceInterface:
    alias: Ivoz\Cgr\Infrastructure\Cgrates\Service\FetchCallStatsService
    public: true

  Ivoz\Cgr\Infrastructure\Cgrates\Service\ProcessExternalCdr: ~

  Ivoz\Cgr\Infrastructure\Cgrates\Service\BillingService:
    public: true

  Ivoz\Cgr\Infrastructure\Cgrates\Service\SetMaxUsageThresholdService:
    public: true

  Ivoz\Cgr\Infrastructure\Cgrates\Service\ReassembleTriggerService:
    public: true

  Ivoz\Cgr\Infrastructure\Cgrates\Service\EnableAccountService:
    public: true

  Ivoz\Cgr\Infrastructure\Cgrates\Service\ReloadService:
    public: true

