#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
  screens: &balanceMovements_screensLink
    balanceMovementsList_screen: &balanceMovementsList_screenLink
      controller: list
      order:
        field:
          - BalanceMovement.createdOn desc
      pagination:
        items: 25
      <<: *BalanceMovements
      class: ui-silk-chart-curve
      title: _("List of %s %2s", ngettext('Balance Movement', 'Balance Movements', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/billing/prepaid_balances.html#balance-movements-list"
      fields: &balanceMovementsList_fieldsLink
        order:
          createdOn: true
          amount: true
          balance: true

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
