#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: brandPortalsList_screen
  screens: &brandPortals_screensLink
    brandPortalsList_screen: &brandPortalsList_screenLink
      controller: list
      forcedValues:
        urlType: brand
      pagination:
        items: 25
      <<: *WebPortals
      class: ui-silk-world-link
      title: _("List of %s %2s", ngettext('Brand Portal', 'Brand Portals', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/brands.html#brand-portals"
      fields: &brandPortals_fieldsLink
        options:
          title: _("Options")
          screens:
            brandPortalsEdit_screen: true
          dialogs:
            brandPortalsDel_dialog: true
          default: brandPortalsEdit_screen
        blacklist:
          klearTheme: true
          userTheme: true
        order: &brandPortalsOrder_Link
          name: true
          urlType: true
          url: true
          logo: true
      options:
        title: _("Options")
        screens:
          brandPortalsNew_screen: true
        dialogs:
          brandPortalsDel_dialog: true
    brandPortalsNew_screen: &brandPortalsNew_screenLink
      <<: *WebPortals
      controller: new
      forcedValues:
        urlType: brand
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Brand Portal', 'Brand Portals', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        order:
          <<: *brandPortalsOrder_Link
      fixedPositions: &brandPortalsFixedPos_Link
        group0:
          colsPerRow: 8
          fields:
            name: 5
            urlType: 2
            url: 7
        group1:
          colsPerRow: 3
          fields:
            klearTheme: 1
            userTheme: 1
            logo: 2
    brandPortalsEdit_screen: &brandPortalsEdit_screenLink
      <<: *WebPortals
      controller: edit
      forcedValues:
        urlType: brand
        userTheme: ''
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Brand Portal', 'Brand Portals', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *brandPortalsOrder_Link
      fixedPositions:
        <<: *brandPortalsFixedPos_Link
  dialogs: &brandPortals_dialogsLink
    brandPortalsDel_dialog: &brandPortalsDel_dialogLink
      <<: *WebPortals
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Brand Portal', 'Brand Portals', 1))
      description: _("Do you want to delete this %s?", ngettext('Brand Portal', 'Brand Portals', 1))
      message: _("%s successfully deleted.", ngettext('Brand Portal', 'Brand Portals', 1))
      multiItem: 1
      labelOnList: 1

  commands: &brandPortals_commandsLink
    brandPortalsLogoDownload_command: &brandPortalsLogoDownload_commandLink
      <<: *WebPortals
      controller: File
      action: force-download
      mainColumn: logo
    webPortalsLogoUpload_command: &webPortalsLogoUpload_commandLink
      <<: *WebPortals
      controller: File
      action: upload
      mainColumn: logo
    webPortalsLogoPreview_command: &webPortalsLogoPreview_commandLink
      <<: *WebPortals
      controller: File
      action: preview
      mainColumn: logo
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
