#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: callACLRelMatchListsList_screen

  screens: &callACLRelMatchLists_screensLink
    callACLRelMatchListsList_screen: &callACLRelMatchListsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *CallAclRelMatchLists
      class: ui-silk-lock-add
      title: _("List of %s %2s", ngettext('Call ACL Pattern', 'Call ACL Patterns', 0), "[format| (%parent%)]")
      fields:
        options:
          title: _("Options")
          screens:
            callACLRelMatchListsEdit_screen: ${auth.acls.CallAclRelMatchLists.update}
          dialogs:
            callACLRelMatchListsDel_dialog: ${auth.acls.CallAclRelMatchLists.delete}
          default: callACLRelMatchListsEdit_screen
      options:
        title: _("Options")
        screens:
          callACLRelMatchListsNew_screen: ${auth.acls.CallAclRelMatchLists.create}
        dialogs:
          callACLRelMatchListsDel_dialog: ${auth.acls.CallAclRelMatchLists.delete}

    callACLRelMatchListsNew_screen: &callACLRelMatchListsNew_screenLink
      <<: *CallAclRelMatchLists
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1))
      shortcutOption: N

    callACLRelMatchListsEdit_screen: &callACLRelMatchListsEdit_screenLink
      <<: *CallAclRelMatchLists
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1), "[format| (%item%)]")

  dialogs: &callACLRelMatchLists_dialogsLink
    callACLRelMatchListsDel_dialog: &callACLRelMatchListsDel_dialogLink
      <<: *CallAclRelMatchLists
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1))
      description: _("Do you want to delete this %s?", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1))
      message: _("%s successfully deleted.", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
