#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: carrierServersList_screen
  screens: &carrierServers_screensLink
    carrierServersList_screen: &carrierServersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *CarrierServers
      class: ui-silk-server
      forcedValues:
        <<: *forcedBrand
      title: _("List of %s %2s", ngettext('Carrier server', 'Carrier servers', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/providers/carriers.html#carrier-servers"
      fields:
        options:
          title: _("Options")
          screens:
            carrierServersEdit_screen: true
          dialogs:
            carrierServersDel_dialog: true
          default: carrierServersEdit_screen
        blacklist:
          domain: true
          transport: true
          uriScheme: true
          authNeeded: true
          authUser: true
          authPassword: true
          sendPAI: true
          sendRPID: true
          hostname: true
          ip: true
          port: true
          fromUser: true
          fromDomain: true
        order:
          sipProxy: true
          outboundProxy: true
          statusIcon: true
      options:
        title: _("Options")
        screens:
          carrierServersNew_screen: true
        dialogs:
          carrierServersDel_dialog: true
    carrierServersNew_screen: &carrierServersNew_screenLink
      <<: *CarrierServers
      forcedValues:
        <<: *forcedBrand
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Carrier server', 'Carrier servers', 1))
      shortcutOption: N
      fields:
        blacklist:
          ip: true
          hostname: true
          port: true
          statusIcon: true
        order: &carrierServersOrder_Link
          sipProxy: true
          authNeeded: true
          sendPAI: true
          fromUser: true
          fromDomain: true
      fixedPositions: &carrierServersFixedPositions_Link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            sipProxy: 4
            outboundProxy: 4
            uriScheme: 2
            transport: 2
        group1:
          label: _("Authentication Settings")
          colsPerRow: 12
          fields:
            authNeeded: 4
            authUser: 4
            authPassword: 4
        group2:
          label: _("Source number header")
          colsPerRow: 2
          collapsed: true
          fields:
            sendPAI: 1
            sendRPID: 1
        group3:
          label: _("From optional customization")
          colsPerRow: 12
          collapsed: true
          fields:
            fromUser: 6
            fromDomain: 6

    carrierServersEdit_screen: &carrierServersEdit_screenLink
      <<: *CarrierServers
      forcedValues:
        <<: *forcedBrand
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Carrier server', 'Carrier servers', 1), "[format| (%item%)]")
      fields:
        blacklist:
          ip: true
          hostname: true
          port: true
          statusIcon: true
        order:
          <<: *carrierServersOrder_Link
      fixedPositions:
        <<: *carrierServersFixedPositions_Link

  dialogs: &carrierServers_dialogsLink
    carrierServersDel_dialog: &carrierServersDel_dialogLink
      <<: *CarrierServers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Carrier server', 'Carrier servers', 1))
      description: _("Do you want to delete this %s?", ngettext('Carrier server', 'Carrier servers', 1))
      message: _("%s successfully deleted.", ngettext('Carrier server', 'Carrier servers', 1))
      multiItem: 1
      labelOnList: 1

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
