#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include PlatformPortalsList.yaml

# This yaml handles CompanyPortals screens
# We call CompanyPortals to the WebPortals that have urlType 'admin' or 'user', so both
# views share the same database table, while the list have special conditions and the
# urlType in CompanyPortals have only 'admin' and 'user' available.

production:
  main:
    module: klearMatrix
    defaultScreen: companyPortalsList_screen
  screens: &companyPortals_screensLink
    companyPortalsList_screen: &companyPortalsList_screenLink
      controller: list
      rawCondition: "WebPortal.urlType IN ('admin', 'user')"
      forcedValues:
        <<: *forcedBrand
      pagination:
        items: 25
      <<: *CompanyPortals
      class: ui-silk-world-link
      title: _("List of %s %2s", ngettext('Company Portal', 'Company Portals', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/settings/client_portals.html"
      fields: &companyPortals_fieldsLink
        options:
          title: _("Options")
          screens:
            companyPortalsEdit_screen: true
          dialogs:
            companyPortalsDel_dialog: true
          default: companyPortalsEdit_screen
        blacklist:
          klearTheme: true
          userTheme: true
        order: &companyPortalsOrder_Link
          name: true
          urlType: true
          url: true
          logo: true
      options:
        title: _("Options")
        screens:
          companyPortalsNew_screen: true
        dialogs:
          companyPortalsDel_dialog: true
    companyPortalsNew_screen: &companyPortalsNew_screenLink
      <<: *CompanyPortals
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Company Portal', 'Company Portals', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields:
        order:
          <<: *companyPortalsOrder_Link
      fixedPositions: &companyPortalsFixedPos_Link
        group0:
          colsPerRow: 8
          fields:
            name: 5
            urlType: 2
            url: 7
        group1:
          colsPerRow: 3
          fields:
            klearTheme: 1
            userTheme: 1
            logo: 2
    companyPortalsEdit_screen: &companyPortalsEdit_screenLink
      <<: *CompanyPortals
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Company Portal', 'Company Portals', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *companyPortalsOrder_Link
      fixedPositions:
        <<: *companyPortalsFixedPos_Link
  dialogs: &companyPortals_dialogsLink
    companyPortalsDel_dialog: &companyPortalsDel_dialogLink
      <<: *CompanyPortals
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Company Portal', 'Company Portals', 1))
      description: _("Do you want to delete this %s?", ngettext('Company Portal', 'Company Portals', 1))
      message: _("%s successfully deleted.", ngettext('Company Portal', 'Company Portals', 1))
      multiItem: 1
      labelOnList: 1

  commands:
    <<: *platformPortals_commandsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
