#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: destinationList_screen
  screens: &destination_screensLink
    destinationList_screen: &destinationList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Destinations
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Destination', 'Destinations', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/billing/destinations.html"
      forcedValues:
        <<: *forcedBrand
      fields: &destination_fieldsLink
        order:
          name: true
          prefix: true
        options:
          title: _("Options")
          screens:
            destinationEdit_screen: true
          dialogs:
            destinationDel_dialog: true
          default: destinationEdit_screen
      options:
        title: _("Options")
        screens:
          destinationNew_screen: true
        dialogs:
          destinationDel_dialog: true

    destinationNew_screen: &destinationNew_screenLink
      <<: *Destinations
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Destination', 'Destinations', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fixedPositions: &destinationFixedPositions_Link
        group1:
          colsPerRow: 9
          fields:
            name: 6
            prefix: 6

    destinationEdit_screen: &destinationEdit_screenLink
      <<: *Destinations
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Destination', 'Destinations', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        readOnly:
          prefix: true
      fixedPositions:
        <<: *destinationFixedPositions_Link

  dialogs: &destination_dialogsLink
    destinationDel_dialog: &destinationDel_dialogLink
      <<: *Destinations
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Destination', 'Destinations', 1))
      description: _("Do you want to delete this %s?", ngettext('Destination', 'Destinations', 1))
      message: _("%s successfully deleted.", ngettext('Destination', 'Destinations', 1))
      multiItem: 1
      labelOnList: 1

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
