#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: domainsList_screen
  screens: &domains_screensLink
    domainsList_screen: &domainsList_screenLink
      controller: list
      rawCondition: "Domain.id NOT IN (1, 2)"
      pagination:
        items: 100
      order:
        field:
        - Domain.domain asc
      <<: *Domains
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Domain', 'Domains', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/sip_domains.html"
      fields:
        order: &domains_orderLink
          domain: true
          brand: true
          client: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
