#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/kamRtpengineHelp.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: kamRtpengineList_screen
  screens: &kamRtpengine_screensLink
    kamRtpengineList_screen: &kamRtpengineList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Rtpengine
      class: ui-silk-bell-link
      title: _("List of %s %2s", ngettext('Media relay', 'Media relays', 0), "[format| (%parent%)]")
      fields: &kamRtpengine_fieldsLink
        options:
          title: _("Options")
          screens:
            kamRtpengineEdit_screen: true
          dialogs:
            kamRtpengineDel_dialog: true
          default: kamRtpengineEdit_screen
      options:
        title: _("Options")
        screens:
          kamRtpengineNew_screen: true
        dialogs:
          kamRtpengineDel_dialog: true
      <<: *kamRtpengineHelp
    kamRtpengineNew_screen: &kamRtpengineNew_screenLink
      <<: *Rtpengine
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Media relay', 'Media relays', 1), "[format| (%parent%)]")
      shortcutOption: N
      fixedPositions: &kamRtpengine_fixedPosition
        group0:
          colsPerRow: 12
          fields:
            disabled: 4
            weight: 5
            url: 9
            description: 8
      <<: *kamRtpengineHelp
    kamRtpengineEdit_screen: &kamRtpengineEdit_screenLink
      <<: *Rtpengine
      controller: edit
      class: ui-silk-pencil
      label: false
      fixedPositions:
        <<: *kamRtpengine_fixedPosition
      labelOnPostAction: _("Edit %s %2s", ngettext('Media relay', 'Media relays', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Media relay', 'Media relays', 1), "[format| (%item%)]")
      <<: *kamRtpengineHelp
  dialogs: &kamRtpengine_dialogsLink
    kamRtpengineDel_dialog: &kamRtpengineDel_dialogLink 
      <<: *Rtpengine
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Media relay', 'Media relays', 1))
      description: _("Do you want to delete this %s?", ngettext('Media relay', 'Media relays', 1))
      message: _("%s successfully deleted.", ngettext('Media relay', 'Media relays', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
