#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: kamTrustedList_screen
  screens: &kamTrusted_screensLink
    kamTrustedList_screen: &kamTrustedList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Trusted
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Trusted IP address', 'Trusted IP addresses', 0), "[format| (%parent%)]")
      rawCondition: "Trusted.company IS NULL"
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/antiflood_trusted_ips.html"
      fields: &kamTrusted_fieldsLink
        options:
          title: _("Options")
          screens:
            kamTrustedEdit_screen: true
          dialogs:
            kamTrustedDel_dialog: true
          default: kamTrustedEdit_screen
        blacklist:
          proto: true
          fromPattern: true
          ruriPattern: true
          priority: true
      options:
        title: _("Options")
        screens:
          kamTrustedNew_screen: true
        dialogs:
          kamTrustedDel_dialog: true
    kamTrustedNew_screen: &kamTrustedNew_screenLink
      <<: *Trusted
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Trusted IP address', 'Trusted IP addresses', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        blacklist:
          proto: true
          fromPattern: true
          ruriPattern: true
          priority: true
    kamTrustedEdit_screen: &kamTrustedEdit_screenLink
      <<: *Trusted
      controller: edit
      class: ui-silk-pencil
      fields:
        blacklist:
          proto: true
          fromPattern: true
          ruriPattern: true
          priority: true
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Trusted IP address', 'Trusted IP addresses', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Trusted IP address', 'Trusted IP addresses', 1), "[format| (%item%)]")
  dialogs: &kamTrusted_dialogsLink
    kamTrustedDel_dialog: &kamTrustedDel_dialogLink 
      <<: *Trusted
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Trusted IP address', 'Trusted IP addresses', 1))
      description: _("Do you want to delete this %s?", ngettext('Trusted IP address', 'Trusted IP addresses', 1))
      message: _("%s successfully deleted.", ngettext('Trusted IP address', 'Trusted IP addresses', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
