#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: kamUsersCdrsList_screen

  screens: &kamUsersCdrs_screensLink
    kamUsersCdrsList_screen: &kamUsersCdrsList_screenLink
      controller: list
      rawCondition: "UsersCdr.startTime >= DATESUB(CURRENT_DATE(), 1, 'YEAR')"
      order:
        field:
          - UsersCdr.startTime desc
      pagination:
        items: 25
      <<: *KamUsersCdrs
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Call', 'Calls', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/calls/call_registry.html"
      forcedValues:
        <<: *forcedCompany
      fields: &kamUsersCdrs_fieldsLink
        blacklist:
          callid: true
          callidHash: true
          xcallid: true
          caller: ${auth.companyVPBX}
          callee: ${auth.companyVPBX}
          party: ${auth.companyNotVPBX}
        order:
          startTime: true
          owner: true
          direction: true
          caller: true
          party: true
          callee: true
          duration: true
        options:
          title: _("Options")
          screens:
            kamUsersCdrsView_screen: true
          default: kamUsersCdrsView_screen

    kamUsersCdrsView_screen: &kamUsersCdrsList_screenLink
      <<: *KamUsersCdrs
      controller: edit
      class: ui-silk-eye
      label: false
      disableSave: true
      labelOnPostAction: _("View %s %2s", ngettext('Call', 'Calls', 1), "[format| (%item%)]")
      title: _("View %s %2s", ngettext('Call', 'Calls', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          callidHash: ${auth.isCompanyOperator}
          callid: ${auth.isCompanyOperator}
          xcallid: ${auth.isCompanyOperator}
          caller: ${auth.companyVPBX}
          callee: ${auth.companyVPBX}
          party: ${auth.companyNotVPBX}
        order:
          startTime: true
          duration: true
          owner: true
          direction: true
          caller: true
          party: true
          callee: true
          callid: true
          callidHash: true
          xcallid: true
      fixedPositions:
        group0:
          label: _("Call Details")
          colsPerRow: 12
          fields:
            startTime: 6
            duration: 6
            owner: 6
            direction: 6
            caller: 6
            party: 6
            callee: 6
        group2:
          label: _("Extra Information")
          colsPerRow: 12
          fields:
            callid: 8
            callidHash: 4
            xcallid: 12

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production

