#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include KamRtpengineList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: mediaRelaySetsList_screen
  screens: &mediaRelaySets_screensLink
    mediaRelaySetsList_screen: &mediaRelaySetsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *MediaRelaySets
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Media relay set', 'Media relay sets', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/infrastructure/media_relay_sets.html"
      fields: &mediaRelaySets_fieldsLink
        options:
          title: _("Options")
          screens:
            mediaRelaySetsEdit_screen: true
            kamRtpengineList_screen: true
          dialogs:
            mediaRelaySetsDel_dialog: true
      options:
        title: _("Options")
        screens:
          mediaRelaySetsNew_screen: true
    mediaRelaySetsNew_screen: &mediaRelaySetsNew_screenLink
      <<: *MediaRelaySets
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Media relay set', 'Media relay sets', 1), "[format| (%parent%)]")
      shortcutOption: N
      fixedPositions: &mediaRelaySetsFixedPositionLink
        group0:
          colsPerRow: 2
          fields:
            name: 1
            description: 2
    mediaRelaySetsEdit_screen: &mediaRelaySetsEdit_screenLink
      <<: *MediaRelaySets
      controller: edit
      class: ui-silk-pencil
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Media relay set', 'Media relay sets', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Media relay set', 'Media relay sets', 1), "[format| (%item%)]")
      fixedPositions:
        <<: *mediaRelaySetsFixedPositionLink

    #kamRtpengine:
    <<: *kamRtpengine_screensLink
    kamRtpengineList_screen:
      <<: *kamRtpengineList_screenLink
      filterField: MediaRelaySet
    kamRtpengineNew_screen:
      <<: *kamRtpengineNew_screenLink
      filterField: MediaRelaySet
    kamRtpengineEdit_screen:
      <<: *kamRtpengineEdit_screenLink
      filterField: MediaRelaySet

  dialogs: &mediaRelaySets_dialogsLink
    mediaRelaySetsDel_dialog: &mediaRelaySetsDel_dialogLink
      <<: *MediaRelaySets
      controller: delete
      class: ui-silk-bin
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      labelOption: false
      title: _("Delete %s", ngettext('Media relay set', 'Media relay sets', 1))
      description: _("Do you want to delete this %s?", ngettext('Media relay set', 'Media relay sets', 1))
      message: _("%s successfully deleted.", ngettext('Media relay set', 'Media relay sets', 1))
      multiItem: 1
      labelOnList: 1

  # kamRtpengine dialogs:
    <<: *kamRtpengine_dialogsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
