#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: pickUpRelUsersList_screen
  screens:
    pickUpRelUsersList_screen: &pickUpRelUsersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *PickUpRelUsers
      title: _("List of %s %2s", ngettext('Pick up rel user', 'Pick up rel users', 0), "[format| (%parent%)]")
      fields:
        options:
          title: _("Options")
          screens:
            pickUpRelUsersEdit_screen: ${auth.acls.PickUpRelUsers.update}
          dialogs:
            pickUpRelUsersDel_dialog: ${auth.acls.PickUpRelUsers.delete}
          default: pickUpRelUsersEdit_screen
      options:
        title: _("Options")
        screens:
          pickUpRelUsersNew_screen: ${auth.acls.PickUpRelUsers.create}
        dialogs:
          pickUpRelUsersDel_dialog: ${auth.acls.PickUpRelUsers.delete}
    pickUpRelUsersNew_screen: &pickUpRelUsersNew_screenLink
      <<: *PickUpRelUsers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Pick up rel user', 'Pick up rel users', 1))
      shortcutOption: N
    pickUpRelUsersEdit_screen: &pickUpRelUsersEdit_screenLink
      <<: *PickUpRelUsers
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Pick up rel user', 'Pick up rel users', 1), "[format| (%item%)]")
  dialogs:
    pickUpRelUsersDel_dialog: &pickUpRelUsersDel_dialogLink
      <<: *PickUpRelUsers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Pick up rel user', 'Pick up rel users', 1))
      description: _("Do you want to delete this %s?", ngettext('Pick up rel user', 'Pick up rel users', 1))
      message: _("%s successfully deleted.", ngettext('Pick up rel user', 'Pick up rel users', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
