#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: platformPortalList_screen
  screens: &platformPortal_screensLink
    platformPortalList_screen: &platformPortalList_screenLink
      controller: list
      forcedValues:
        urlType: god
      pagination:
        items: 25
      <<: *WebPortals
      class: ui-silk-world-link
      title: _("List of %s %2s", ngettext('Platform Portal', 'Platform Portals', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/portals.html"
      fields: &platformPortal_fieldsLink
        options:
          title: _("Options")
          screens:
            platformPortalEdit_screen: true
          dialogs:
            platformPortalDel_dialog: true
          default: platformPortalEdit_screen
        blacklist:
          klearTheme: true
          brand: true
        order: &platformPortalOrder_Link
          name: true
          urlType: true
          url: true
          logo: true
      options:
        title: _("Options")
        screens:
          platformPortalNew_screen: true
        dialogs:
          platformPortalDel_dialog: true
    platformPortalNew_screen: &platformPortalNew_screenLink
      <<: *WebPortals
      controller: new
      forcedValues:
        urlType: god
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Platform Portal', 'Platform Portals', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        blacklist:
          brand: true
        order:
          <<: *platformPortalOrder_Link
      fixedPositions: &platformPortalFixedPos_Link
        group0:
          colsPerRow: 8
          fields:
            name: 5
            urlType: 2
            url: 7
        group1:
          colsPerRow: 3
          fields:
            klearTheme: 1
            userTheme: 1
            logo: 2
    platformPortalEdit_screen: &platformPortalEdit_screenLink
      <<: *WebPortals
      controller: edit
      forcedValues:
        urlType: god
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Platform Portal', 'Platform Portals', 1), "[format| (%item%)]")
      fields:
        blacklist:
          brand: true
        order:
          <<: *platformPortalOrder_Link
      fixedPositions:
        <<: *platformPortalFixedPos_Link
  dialogs: &platformPortal_dialogsLink
    platformPortalDel_dialog: &platformPortalDel_dialogLink
      <<: *WebPortals
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Platform Portal', 'Platform Portals', 1))
      description: _("Do you want to delete this %s?", ngettext('Platform Portal', 'Platform Portals', 1))
      message: _("%s successfully deleted.", ngettext('Platform Portal', 'Platform Portals', 1))
      multiItem: 1
      labelOnList: 1

  commands: &platformPortals_commandsLink
    webPortalsLogoDownload_command: &webPortalsLogoDownload_commandLink
      <<: *WebPortals
      controller: File
      action: force-download
      mainColumn: logo
    webPortalsLogoUpload_command: &webPortalsLogoUpload_commandLink
      <<: *WebPortals
      controller: File
      action: upload
      mainColumn: logo
    webPortalsLogoPreview_command: &webPortalsLogoPreview_commandLink
      <<: *WebPortals
      controller: File
      action: preview
      mainColumn: logo
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
