#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include RatingProfilesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: ratingProfilesList_screen

  screens:
    <<: *ratingProfiles_screensLink
    ratingProfilesList_screen:
      <<: *ratingProfilesList_screenLink
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/rating_profiles.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        <<: *ratingProfiles_fieldsLink
        options:
          title: _("Options")
          dialogs:
            exportRatingPlansToCsv_dialog: true
      options:
        title: _("Options")
        dialogs:
          simulateCall_dialog: true

  dialogs:
    <<: *ratingProfiles_dialogsLink
    simulateCall_dialog:
      <<: *simulateCall_dialogLink
      forcedValues:
        parentId: ${auth.companyId}
  commands:
    <<: *ratingProfiles_commandLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
