#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: ratingPlansList_screen
  screens: &ratingPlans_screensLink
    ratingPlansList_screen: &ratingPlansList_screenLink
      controller: list
      order:
        field:
          - RatingPlan.weight desc
      pagination:
        items: 25
      <<: *RatingPlans
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Destination rate', 'Destination rates', 0), "[format| (%parent%)]")
      fields: &ratingPlans_fieldsLink
        order:
          tag: true
          name: true
          description: true
        options:
          title: _("Options")
          screens:
            ratingPlansEdit_screen: true
          dialogs:
            ratingPlansDel_dialog: true
          default: ratingPlansEdit_screen
      options:
        title: _("Options")
        screens:
          ratingPlansNew_screen: true
        dialogs:
          ratingPlansDel_dialog: true
          simulateRatingPlanCall_dialog: true

    ratingPlansNew_screen: &ratingPlansNew_screenLink
      <<: *RatingPlans
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Destination rate', 'Destination rates', 1), "[format| (%parent%)]")
      shortcutOption: N
      fixedPositions: &ratingPlans_fixedPositionsLink
        group1:
          colsPerRow: 4
          fields:
            destinationRateGroup: 3
            weight: 1
        group2:
          colsPerRow: 6
          fields:
            timingType: 3
            timeIn: 3
            monday: 1
            tuesday: 1
            wednesday: 1
            thursday: 1
            friday: 1
            saturday: 1
            sunday: 1

    ratingPlansEdit_screen: &ratingPlansEdit_screenLink
      <<: *RatingPlans
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Destination rate', 'Destination rates', 1), "[format| (%item%)]")
      fixedPositions:
        <<: *ratingPlans_fixedPositionsLink

  dialogs: &ratingPlans_dialogsLink
    ratingPlansDel_dialog: &ratingPlansDel_dialogLink
      <<: *RatingPlans
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Destination rate', 'Destination rates', 1))
      description: _("Do you want to delete this %s?", ngettext('Destination rate', 'Destination rates', 1))
      message: _("%s successfully deleted.", ngettext('Destination rate', 'Destination rates', 1))
      multiItem: 1
      labelOnList: 1

    simulateRatingPlanCall_dialog: &simulateRatingPlanCall_dialogLink
      <<: *DestinationRates
      module: default
      title: _("Simulate a call")
      label: false
      labelOnEdit: false
      labelOnList: true
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-tarificator
      action: test-rating-plan
      class:  ui-silk-telephone

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
