#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: routingTagsList_screen
  screens: &routingTags_screensLink
    routingTagsList_screen: &routingTagsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RoutingTags
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Routing Tag', 'Routing Tags', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/routing/routing_tags.html"
      forcedValues:
        <<: *forcedBrand
      fields: &routingTags_fieldsLink
        options:
          title: _("Options")
          screens:
            routingTagsEdit_screen: true
          dialogs:
            routingTagsDel_dialog: true
          default: routingTagsEdit_screen
      options:
        title: _("Options")
        screens:
          routingTagsNew_screen: true
        dialogs:
          routingTagsDel_dialog: true
    routingTagsNew_screen: &routingTagsNew_screenLink
      <<: *RoutingTags
      controller: new
      class: ui-silk-add
      forcedValues:
        <<: *forcedBrand
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Routing Tag', 'Routing Tags', 1), "[format| (%parent%)]")
      shortcutOption: N
    routingTagsEdit_screen: &routingTagsEdit_screenLink
      <<: *RoutingTags
      controller: edit
      class: ui-silk-pencil
      forcedValues:
        <<: *forcedBrand
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Routing Tag', 'Routing Tags', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Routing Tag', 'Routing Tags', 1), "[format| (%item%)]")

  dialogs: &routingTags_dialogsLink
    routingTagsDel_dialog: &routingTagsDel_dialogLink
      <<: *RoutingTags
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Routing Tag', 'Routing Tags', 1))
      description: _("Do you want to delete this %s?", ngettext('Routing Tag', 'Routing Tags', 1))
      message: _("%s successfully deleted.", ngettext('Routing Tag', 'Routing Tags', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
