api:
  resource: '.'
  type: 'api_platform'

api_base_path:
  path: '/'

api_admin_login:
  path: admin_login

api_user_login:
  path: user_login

###############################
## Refresh JWT Token
###############################
gesdinet_jwt_refresh_token:
  path:     /token/refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

###############################
## Custom routes
###############################
get_my_active_calls:
  path: '/my/active_calls'
  methods: ['GET']
  defaults:
    _controller: Controller\My\ActiveCallsAction
    _api_resource_class: 'Model\ActiveCalls'
    _api_item_operation_name: 'get_my_active_calls'
    _api_receive: false

put_billable_call_rate_by_callid:
  path: '/billable_calls/{callid}/rate'
  methods: ['PUT']
  defaults:
    _controller: Controller\Provider\PutBillableCallRatingAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\BillableCall\BillableCall'
    _api_item_operation_name: 'put_billable_call_rate_by_callid'
    _api_receive: false
