# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: "@ApiBundle/Resources/config/services.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Service\UserProvider:
    arguments:
      $identifierField: 'username'
      $entityClass: 'Ivoz\Provider\Domain\Model\Administrator\Administrator'

  Service\AuthEndpointDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 5
    arguments:
      $decoratedNormalizer:
        '@Service\AuthEndpointDecorator.inner'

  Ivoz\Api\Core\Security\DataAccessControlParser: ~

  #######################################
  ## Controllers
  #######################################
  Controller\My\:
    resource: '../src/Controller/My/*'
    tags: ['controller.service_arguments']

  Controller\Provider\:
    resource: '../src/Controller/Provider/*'
    tags: ['controller.service_arguments']
