parameters:
    sentinels:
      - {host: 'data.ivozprovider.local', port: '26379'}
    ws_host: '127.0.0.1'
    ws_port: 8081
    ws_worker_num: 1

    # per worker
    # 3 at least because 2 are used by the service itself
    redis_pool_size: 52
    redis_db: 1

    logger_level: info