Ivoz\Kam\Domain\Model\TrunksAddress\TrunksAddress:
  repositoryClass: Ivoz\Kam\Infrastructure\Persistence\Doctrine\TrunksAddressDoctrineRepository
  type: entity
  table: kam_trunks_address
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
