Ivoz\Kam\Domain\Model\TrunksCdr\TrunksCdrAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    trunksCdr_callid_direction:
      columns:
        - callid
        - direction
  indexes:
    trunksCdr_start_time_idx:
      columns:
      - start_time
    trunksCdr_parsed_idx:
      columns:
        - parsed
  fields:
    startTime:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
      column: start_time
    endTime:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
      column: end_time
    duration:
      type: float
      nullable: false
      precision: 10
      scale: 3
      options:
        default: 0.0
    caller:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    callee:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    callid:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    callidHash:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: callidHash
    xcallid:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    diversion:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    bounced:
      type: boolean
      nullable: true
    parsed:
      type: boolean
      nullable: true
      options:
        default: '0'
    parserScheduledAt:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: parserScheduledAt
    direction:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        comment: '[enum:inbound|outbound]'
    cgrid:
      type: string
      nullable: true
      length: 40
      options:
        fixed: false
      column: cgrid
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        carrierId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    retailAccount:
      targetEntity: \Ivoz\Provider\Domain\Model\RetailAccount\RetailAccountInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        retailAccountId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    residentialDevice:
      targetEntity: \Ivoz\Provider\Domain\Model\ResidentialDevice\ResidentialDeviceInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        residentialDeviceId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    user:
      targetEntity: \Ivoz\Provider\Domain\Model\User\UserInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        userId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    friend:
      targetEntity: \Ivoz\Provider\Domain\Model\Friend\FriendInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        friendId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    fax:
      targetEntity: \Ivoz\Provider\Domain\Model\Fax\FaxInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        faxId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    ddi:
      targetEntity: \Ivoz\Provider\Domain\Model\Ddi\DdiInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        ddiId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    ddiProvider:
      targetEntity: \Ivoz\Provider\Domain\Model\DdiProvider\DdiProviderInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        ddiProviderId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
