Ivoz\Provider\Domain\Model\Administrator\Administrator:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\AdministratorDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Administrators
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    relPublicEntities:
      targetEntity: Ivoz\Provider\Domain\Model\AdministratorRelPublicEntity\AdministratorRelPublicEntityInterface
      mappedBy: administrator
