Ivoz\Provider\Domain\Model\AdministratorRelPublicEntity\AdministratorRelPublicEntityAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    administratorRelPublicEntity_administrator_publicEntity:
      columns:
        - administratorId
        - publicEntityId
  fields:
    create:
      type: boolean
      nullable: false
      options:
        default: '0'
      column: '`create`'
    read:
      type: boolean
      nullable: false
      options:
        default: '1'
      column: '`read`'
    update:
      type: boolean
      nullable: false
      options:
        default: '0'
      column: '`update`'
    delete:
      type: boolean
      nullable: false
      options:
        default: '0'
      column: '`delete`'
  manyToOne:
    administrator:
      targetEntity: \Ivoz\Provider\Domain\Model\Administrator\AdministratorInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: relPublicEntities
      joinColumns:
        administratorId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    publicEntity:
      targetEntity: \Ivoz\Provider\Domain\Model\PublicEntity\PublicEntityInterface
      cascade: {  }
      fetch: EAGER
      mappedBy: null
      inversedBy: null
      joinColumns:
        publicEntityId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
