Ivoz\Provider\Domain\Model\ApplicationServer\ApplicationServer:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ApplicationServerDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: ApplicationServers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
