Ivoz\Provider\Domain\Model\BalanceNotification\BalanceNotification:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\BalanceNotificationDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: BalanceNotifications
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
