Ivoz\Provider\Domain\Model\BalanceMovement\BalanceMovement:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\BalanceMovementDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: BalanceMovements
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
