Ivoz\Provider\Domain\Model\BalanceMovement\BalanceMovementAbstract:
  type: mappedSuperclass
  fields:
    amount:
      type: decimal
      nullable: true
      precision: 10
      scale: 4
      options:
        default: 0
      column: amount
    balance:
      type: decimal
      nullable: true
      precision: 10
      scale: 4
      options:
        default: 0
      column: balance
    createdOn:
      type: datetime
      nullable: true
      options:
        default: CURRENT_TIMESTAMP
      column: createdOn
  manyToOne:
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        carrierId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false