Ivoz\Provider\Domain\Model\BannedAddress\BannedAddressAbstract:
  type: mappedSuperclass
  indexes:
    bannedAddress_lastTimeBanned:
      columns:
      - lastTimeBanned
    bannedAddress_ip_blocker:
      columns:
      - ip
      - blocker
  fields:
    ip:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
    blocker:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
        comment: '[enum:antiflood|ipfilter]'
      column: blocker
    description:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
    lastTimeBanned:
      type: datetime
      nullable: true
      column: lastTimeBanned
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
