Ivoz\Provider\Domain\Model\BannedAddress\BannedAddress:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\BannedAddressDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: BannedAddresses
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
