Ivoz\Provider\Domain\Model\BillableCall\BillableCall:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\BillableCallDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: BillableCalls
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
