Ivoz\Provider\Domain\Model\BrandService\BrandService:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\BrandServiceDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: BrandServices
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
