Ivoz\Provider\Domain\Model\Brand\Brand:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\BrandDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Brands
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    companies:
      targetEntity: Ivoz\Provider\Domain\Model\Company\CompanyInterface
      mappedBy: brand
    services:
      targetEntity: Ivoz\Provider\Domain\Model\BrandService\BrandServiceInterface
      mappedBy: brand
    urls:
      targetEntity: Ivoz\Provider\Domain\Model\WebPortal\WebPortalInterface
      mappedBy: brand
    relFeatures:
      targetEntity: Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrandInterface
      mappedBy: brand
      cascade: ['persist']
      orphanRemoval: true
    relProxyTrunks:
      targetEntity: Ivoz\Provider\Domain\Model\ProxyTrunksRelBrand\ProxyTrunksRelBrandInterface
      mappedBy: brand
      cascade: ['persist']
      orphanRemoval: true
    residentialDevices:
      targetEntity: Ivoz\Provider\Domain\Model\ResidentialDevice\ResidentialDeviceInterface
      mappedBy: brand
    musicsOnHold:
      targetEntity: Ivoz\Provider\Domain\Model\MusicOnHold\MusicOnHoldInterface
      mappedBy: brand
    matchLists:
      targetEntity: Ivoz\Provider\Domain\Model\MatchList\MatchListInterface
      mappedBy: brand
    outgoingRoutings:
      targetEntity: Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRoutingInterface
      mappedBy: brand
