Ivoz\Provider\Domain\Model\CalendarPeriodsRelSchedule\CalendarPeriodsRelSchedule:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CalendarPeriodsRelScheduleDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CalendarPeriodsRelSchedules
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
