Ivoz\Provider\Domain\Model\CalendarPeriod\CalendarPeriodAbstract:
  type: mappedSuperclass
  fields:
    startDate:
      type: date
      nullable: false
      column: startDate
    endDate:
      type: date
      nullable: false
      column: endDate
    routeType:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
        comment: '[enum:number|extension|voicemail]'
      column: routeType
    numberValue:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
      column: numberValue
  manyToOne:
    calendar:
      targetEntity: \Ivoz\Provider\Domain\Model\Calendar\CalendarInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: calendarPeriods
      joinColumns:
        calendarId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    locution:
      targetEntity: \Ivoz\Provider\Domain\Model\Locution\LocutionInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        locutionId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    extension:
      targetEntity: \Ivoz\Provider\Domain\Model\Extension\ExtensionInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        extensionId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    voiceMailUser:
      targetEntity: \Ivoz\Provider\Domain\Model\User\UserInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        voiceMailUserId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    numberCountry:
      targetEntity: \Ivoz\Provider\Domain\Model\Country\CountryInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        numberCountryId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false