Ivoz\Provider\Domain\Model\Calendar\Calendar:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CalendarDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Calendars
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    holidayDates:
      targetEntity: Ivoz\Provider\Domain\Model\HolidayDate\HolidayDateInterface
      mappedBy: calendar
    calendarPeriods:
      targetEntity: Ivoz\Provider\Domain\Model\CalendarPeriod\CalendarPeriodInterface
      mappedBy: calendar