Ivoz\Provider\Domain\Model\CalendarPeriod\CalendarPeriod:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CalendarPeriodDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CalendarPeriods
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    relSchedules:
      targetEntity: Ivoz\Provider\Domain\Model\CalendarPeriodsRelSchedule\CalendarPeriodsRelScheduleInterface
      mappedBy: calendarPeriod
      cascade: ['persist']
      orphanRemoval: true