Ivoz\Provider\Domain\Model\CallCsvReport\Csv:
  type: embeddable
  fields:
    fileSize:
      type: integer
      nullable: true
      options:
        unsigned: true
        comment: '[FSO]'
      column: csvFileSize
    mimeType:
      type: string
      nullable: true
      length: 80
      options:
        fixed: false
      column: csvMimeType
    baseName:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: csvBaseName
