Ivoz\Provider\Domain\Model\CallCsvReport\CallCsvReport:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CallCsvReportDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CallCsvReports
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
