Ivoz\Provider\Domain\Model\CarrierServer\CarrierServer:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CarrierServerDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CarrierServers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
