Ivoz\Provider\Domain\Model\CarrierServer\CarrierServerAbstract:
  type: mappedSuperclass
  fields:
    ip:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
    hostname:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    port:
      type: smallint
      nullable: true
      options:
        unsigned: true
    uriScheme:
      type: smallint
      nullable: true
      options:
        unsigned: true
      column: uriScheme
    transport:
      type: smallint
      nullable: true
      options:
        unsigned: true
    sendPAI:
      type: boolean
      nullable: true
      options:
        default: 0
        unsigned: true
      column: sendPAI
    sendRPID:
      type: boolean
      nullable: true
      options:
        default: 0
        unsigned: true
      column: sendRPID
    authNeeded:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        default: 'no'
      column: authNeeded
    authUser:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: authUser
    authPassword:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: authPassword
    sipProxy:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: sipProxy
    outboundProxy:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: outboundProxy
    fromUser:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: fromUser
    fromDomain:
      type: string
      nullable: true
      length: 190
      options:
        fixed: false
      column: fromDomain
  manyToOne:
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: servers
      joinColumns:
        carrierId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
  oneToOne:
    lcrGateway:
      targetEntity: Ivoz\Kam\Domain\Model\TrunksLcrGateway\TrunksLcrGatewayInterface
      mappedBy: carrierServer
      fetch: LAZY

