Ivoz\Provider\Domain\Model\CompanyRelCodec\CompanyRelCodec:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CompanyRelCodecDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CompaniesRelCodecs
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
