Ivoz\Provider\Domain\Model\CompanyService\CompanyService:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CompanyServiceDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CompanyServices
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
