Ivoz\Provider\Domain\Model\CompanyRelGeoIPCountry\CompanyRelGeoIPCountry:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CompanyRelGeoIPCountryDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CompaniesRelGeoIPCountries
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
