Ivoz\Provider\Domain\Model\CompanyRelGeoIPCountry\CompanyRelGeoIPCountryAbstract:
  type: mappedSuperclass
  manyToOne:
    company:
      targetEntity: Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: relCountries
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    country:
      targetEntity: Ivoz\Provider\Domain\Model\Country\CountryInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        countryId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
