Ivoz\Provider\Domain\Model\CompanyRelRoutingTag\CompanyRelRoutingTag:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CompanyRelRoutingTagDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: CompaniesRelRoutingTags
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
