Ivoz\Provider\Domain\Model\ConferenceRoom\ConferenceRoom:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ConferenceRoomDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: ConferenceRooms
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
