Ivoz\Provider\Domain\Model\Country\Country:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\CountryDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Countries
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
