Ivoz\Provider\Domain\Model\Ddi\Ddi:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\DdiDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: DDIs
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
