Ivoz\Provider\Domain\Model\DdiProviderRegistration\DdiProviderRegistration:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\DdiProviderRegistrationDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: DDIProviderRegistrations
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY