Ivoz\Provider\Domain\Model\DdiProviderAddress\DdiProviderAddressAbstract:
  type: mappedSuperclass
  fields:
    ip:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
    description:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
  manyToOne:
    ddiProvider:
      targetEntity: \Ivoz\Provider\Domain\Model\DdiProvider\DdiProviderInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: ddiProviderAddresses
      joinColumns:
        ddiProviderId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
  oneToOne:
    trunksAddress:
      targetEntity: Ivoz\Kam\Domain\Model\TrunksAddress\TrunksAddressInterface
      mappedBy: ddiProviderAddress
      fetch: LAZY
