Ivoz\Provider\Domain\Model\DdiProviderAddress\DdiProviderAddress:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\DdiProviderAddressDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: DDIProviderAddresses
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
