Ivoz\Provider\Domain\Model\DestinationRate\DestinationRateAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    destinationRate_destination:
      unique: true
      columns:
        - destinationRateGroupId
        - destinationId
  fields:
    cost:
      type: decimal
      nullable: false
      precision: 10
      scale: 4
      column: rate
    connectFee:
      type: decimal
      nullable: false
      precision: 10
      scale: 4
      column: connectFee
    rateIncrement:
      type: string
      nullable: false
      length: 16
      options:
        fixed: false
      column: rateIncrement
    groupIntervalStart:
      type: string
      nullable: false
      length: 16
      options:
        fixed: false
        default: "0s"
      column: groupIntervalStart
  manyToOne:
    destinationRateGroup:
      targetEntity: \Ivoz\Provider\Domain\Model\DestinationRateGroup\DestinationRateGroupInterface
      mappedBy: null
      inversedBy: destinationRates
      joinColumns:
        destinationRateGroupId:
          nullable: false
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    destination:
      targetEntity: \Ivoz\Provider\Domain\Model\Destination\DestinationInterface
      mappedBy: null
      inversedBy: destinationRates
      joinColumns:
        destinationId:
          nullable: false
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
  oneToOne:
    tpRate:
      targetEntity: Ivoz\Cgr\Domain\Model\TpRate\TpRateInterface
      mappedBy: destinationRate
      fetch: LAZY
    tpDestinationRate:
      targetEntity: Ivoz\Cgr\Domain\Model\TpDestinationRate\TpDestinationRateInterface
      mappedBy: destinationRate
      fetch: LAZY