Ivoz\Provider\Domain\Model\Destination\Destination:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\DestinationDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Destinations
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    destinationRates:
      targetEntity: Ivoz\Provider\Domain\Model\DestinationRate\DestinationRateInterface
      mappedBy: destination