Ivoz\Provider\Domain\Model\DestinationRate\DestinationRate:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\DestinationRateDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: DestinationRates
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
