Ivoz\Provider\Domain\Model\Destination\DestinationAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    destination_prefix_brand:
      columns:
        - prefix
        - brandId
  embedded:
    name:
      class: Name
      columnPrefix: false
  fields:
    prefix:
      type: string
      nullable: false
      length: 24
      options:
        fixed: false
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
  oneToOne:
    tpDestination:
      targetEntity: \Ivoz\Cgr\Domain\Model\TpDestination\TpDestinationInterface
      mappedBy: destination
      fetch: LAZY
