Ivoz\Provider\Domain\Model\Domain\Domain:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\DomainDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Domains
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    friends:
      targetEntity: Ivoz\Provider\Domain\Model\Friend\FriendInterface
      mappedBy: domain
    residentialDevices:
      targetEntity: Ivoz\Provider\Domain\Model\ResidentialDevice\ResidentialDeviceInterface
      mappedBy: domain
    terminals:
      targetEntity: Ivoz\Provider\Domain\Model\Terminal\TerminalInterface
      mappedBy: domain
