Ivoz\Provider\Domain\Model\Extension\Extension:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ExtensionDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Extensions
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    users:
      targetEntity: Ivoz\Provider\Domain\Model\User\UserInterface
      mappedBy: extension
