Ivoz\Provider\Domain\Model\FaxesInOut\FaxesInOut:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\FaxesInOutDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: FaxesInOut
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
