Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrand:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\FeaturesRelBrandDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: FeaturesRelBrands
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
