Ivoz\Provider\Domain\Model\Feature\Feature:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\FeatureDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Features
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
