Ivoz\Provider\Domain\Model\FixedCost\FixedCost:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\FixedCostDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: FixedCosts
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
