Ivoz\Provider\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoice:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\FixedCostsRelInvoiceDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: FixedCostsRelInvoices
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
