Ivoz\Provider\Domain\Model\FriendsPattern\FriendsPattern:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\FriendsPatternDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: FriendsPatterns
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
