Ivoz\Provider\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUser:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\HuntGroupsRelUserDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: HuntGroupsRelUsers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
