Ivoz\Provider\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUserAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    userHuntgroup:
      columns:
        - userId
        - huntGroupId
    prioHuntgroup:
      columns:
        - priority
        - huntGroupId
  fields:
    timeoutTime:
      type: smallint
      nullable: true
      options:
        unsigned: false
      column: timeoutTime
    priority:
      type: smallint
      nullable: true
      options:
        unsigned: false
    routeType:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
        comment: '[enum:number|user]'
      column: routeType
    numberValue:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
      column: numberValue
  manyToOne:
    huntGroup:
      targetEntity: \Ivoz\Provider\Domain\Model\HuntGroup\HuntGroupInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: huntGroupsRelUsers
      joinColumns:
        huntGroupId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    user:
      targetEntity: \Ivoz\Provider\Domain\Model\User\UserInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        userId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    numberCountry:
      targetEntity: \Ivoz\Provider\Domain\Model\Country\CountryInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        numberCountryId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false