Ivoz\Provider\Domain\Model\InvoiceTemplate\InvoiceTemplate:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\InvoiceTemplateDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: InvoiceTemplates
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
