Ivoz\Provider\Domain\Model\InvoiceNumberSequence\InvoiceNumberSequence:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\InvoiceNumberSequenceDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: InvoiceNumberSequences
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
