Ivoz\Provider\Domain\Model\IvrExcludedExtension\IvrExcludedExtension:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\IvrExcludedExtensionDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: IVRExcludedExtensions
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
