Ivoz\Provider\Domain\Model\Locution\Locution:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\LocutionDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Locutions
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
