Ivoz\Provider\Domain\Model\MatchList\MatchList:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\MatchListDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: MatchLists
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    patterns:
      targetEntity: Ivoz\Provider\Domain\Model\MatchListPattern\MatchListPatternInterface
      mappedBy: matchList
