Ivoz\Provider\Domain\Model\MusicOnHold\MusicOnHold:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\MusicOnHoldDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: MusicOnHold
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
