Ivoz\Provider\Domain\Model\OutgoingRoutingRelCarrier\OutgoingRoutingRelCarrierAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    outgoingRoutingRelCarrier_carrier:
      columns:
        - outgoingRoutingId
        - carrierId
  manyToOne:
    outgoingRouting:
      targetEntity: \Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRoutingInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: relCarriers
      joinColumns:
        outgoingRoutingId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: outgoingRoutingsRelCarriers
      joinColumns:
        carrierId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
