Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRouting:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\OutgoingRoutingDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: OutgoingRouting
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    lcrRules:
      targetEntity: Ivoz\Kam\Domain\Model\TrunksLcrRule\TrunksLcrRuleInterface
      mappedBy: outgoingRouting
    lcrRuleTargets:
      targetEntity: Ivoz\Kam\Domain\Model\TrunksLcrRuleTarget\TrunksLcrRuleTargetInterface
      mappedBy: outgoingRouting
    relCarriers:
      targetEntity: Ivoz\Provider\Domain\Model\OutgoingRoutingRelCarrier\OutgoingRoutingRelCarrierInterface
      mappedBy: outgoingRouting
      cascade: ['persist']
      orphanRemoval: true
  oneToOne:
    tpLcrRule:
      targetEntity: Ivoz\Cgr\Domain\Model\TpLcrRule\TpLcrRuleInterface
      mappedBy: outgoingRouting
      fetch: LAZY