Ivoz\Provider\Domain\Model\OutgoingDdiRulesPattern\OutgoingDdiRulesPattern:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\OutgoingDdiRulesPatternDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: OutgoingDDIRulesPatterns
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
