Ivoz\Provider\Domain\Model\OutgoingRoutingRelCarrier\OutgoingRoutingRelCarrier:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\OutgoingRoutingRelCarrierDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: OutgoingRoutingRelCarriers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    tpRatingProfiles:
      targetEntity: Ivoz\Cgr\Domain\Model\TpRatingProfile\TpRatingProfileInterface
      mappedBy: outgoingRoutingRelCarrier
