Ivoz\Provider\Domain\Model\PickUpRelUser\PickUpRelUser:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\PickUpRelUserDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: PickUpRelUsers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
