Ivoz\Provider\Domain\Model\PickUpGroup\PickUpGroup:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\PickUpGroupDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: PickUpGroups
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    relUsers:
      targetEntity: Ivoz\Provider\Domain\Model\PickUpRelUser\PickUpRelUser
      mappedBy: pickUpGroup
      cascade: ['persist']
      orphanRemoval: true
