Ivoz\Provider\Domain\Model\ProxyTrunksRelBrand\ProxyTrunksRelBrandAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    proxyTrunkRelBrand_proxyTrunk_brand:
      columns:
        - proxyTrunkId
        - brandId
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: relProxyTrunks
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    proxyTrunk:
      targetEntity: \Ivoz\Provider\Domain\Model\ProxyTrunk\ProxyTrunkInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        proxyTrunkId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
