Ivoz\Provider\Domain\Model\ProxyTrunksRelBrand\ProxyTrunksRelBrand:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ProxyTrunksRelBrandDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: ProxyTrunksRelBrands
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
