Ivoz\Provider\Domain\Model\ProxyUser\ProxyUser:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ProxyUserDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: ProxyUsers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
