Ivoz\Provider\Domain\Model\Queue\Queue:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\QueueDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Queues
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
