Ivoz\Provider\Domain\Model\QueueMember\QueueMember:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\QueueMemberDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: QueueMembers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
