Ivoz\Provider\Domain\Model\RatingPlanGroup\RatingPlanGroup:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\RatingPlanGroupDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: RatingPlanGroups
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    ratingPlan:
      targetEntity: \Ivoz\Provider\Domain\Model\RatingPlan\RatingPlanInterface
      mappedBy: ratingPlanGroup
