Ivoz\Provider\Domain\Model\RatingProfile\RatingProfileAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    ratingProfile_company_plan_tag:
      columns:
        - companyId
        - ratingPlanGroupId
        - routingTagId
        - activationTime
  fields:
    activationTime:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: activationTime
  manyToOne:
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: ratingProfiles
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: ratingProfiles
      joinColumns:
        carrierId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    ratingPlanGroup:
      targetEntity: \Ivoz\Provider\Domain\Model\RatingPlanGroup\RatingPlanGroupInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        ratingPlanGroupId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    routingTag:
      targetEntity: \Ivoz\Provider\Domain\Model\RoutingTag\RoutingTagInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        routingTagId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
