Ivoz\Provider\Domain\Model\Recording\Recording:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\RecordingDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Recordings
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
