Ivoz\Provider\Domain\Model\Schedule\Schedule:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ScheduleDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Schedules
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
