Ivoz\Provider\Domain\Model\Service\Service:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\ServiceDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Services
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
