Ivoz\Provider\Domain\Model\SpecialNumber\SpecialNumber:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\SpecialNumberDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: SpecialNumbers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
