Ivoz\Provider\Domain\Model\SpecialNumber\SpecialNumberAbstract:
  type: mappedSuperclass
  fields:
    number:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
      column: number
    numberE164:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
      column: numberE164
    disableCDR:
      type: integer
      nullable: false
      options:
        default: 1
        unsigned: true
      column: disableCDR
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    country:
      targetEntity: \Ivoz\Provider\Domain\Model\Country\CountryInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        countryId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
