Ivoz\Provider\Domain\Model\TerminalModel\TerminalModel:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\TerminalModelDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: TerminalModels
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
