Ivoz\Provider\Domain\Model\Timezone\Timezone:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\TimezoneDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: Timezones
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
