Ivoz\Provider\Domain\Model\TransformationRule\TransformationRule:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\TransformationRuleDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: TransformationRules
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
