Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSet:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\TransformationRuleSetDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: TransformationRuleSets
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    rules:
      targetEntity: Ivoz\Provider\Domain\Model\TransformationRule\TransformationRuleInterface
      mappedBy: transformationRuleSet
