Ivoz\Provider\Domain\Model\WebPortal\WebPortal:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\WebPortalDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: WebPortals
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
