##
## Global configuration for GearmanBundle
##
## http://gearmanbundle.readthedocs.io/en/latest/configuration.html
##
gearman:
  servers:
    jobs.ivozprovider.local:
       host: jobs.ivozprovider.local
  resources:
    - ../src/Worker/

doctrine_cache:
  providers:
    gearman_cache:
      type: file_system
      namespace: doctrine_cache.ns.gearman